# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a00b8f066db0851341595075c3b700bc76e6f1e62618d3776304e39cd6708fe15990ce9b956b36857254329507ea4f08a7029e3712afc74e12ec6a4577f6ddbd

test:
  secret_key_base: fcac81044ac67292b0440fd29a5108fc9139b2c18dd49d4f5b3af78472c7f18750f040dc2d86a353cf957d90618ec6abb3c3a04082db402c0b9902a85ec85650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
